import localFont from "next/font/local";
import Navigation from "@/components/common/Navigation";
import Footer from "@/components/common/Footer";
import "./../globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
